version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=my-secure-password
      - POSTGRES_DB=nest-api
      - TZ=America/Sao_Paulo

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: